# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My site (in progress)
author: Ike Y.
email: ikeyuan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  No current aim for this site at the moment,
  just setting up formatting and the like.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ikii.github.io" # the base hostname & protocol for your site
twitter_username: iyku
github_username:  ikii

# Build settings
markdown: kramdown
